org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=false
org.gradle.daemon=false
org.gradle.workers.max=1
kotlin.compiler.execution.strategy=in-process
android.builtInKotlin=false
android.newDsl=false
